export const NavigateTo = {
  LANDING_SCREEN: 'LANDING_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',
};

export const CHAT_APPLICATION_ID = 6860;
export const CHAT_AUTH_KEY = 'r8GNG7EcRLHcES5';
export const CHAT_AUTH_SECRET = 'VaYRzHtEvEkQL6L';
